<?php
if(!empty($this->view->dados)){
    $item = $this->view->dados;
} else {
    $item = "";
}
?>
<!-- Booking Section-->
<section id="booking" class="booking">
  <div class="container text-center">
    <header>
      <h2>Cadastre-se</h2>
    </header>
    <div class="row">
      <div class="form-holder col-lg-10 mx-auto text-center">
        <div class="ribbon"><i class="icon-lock"></i></div>
        <h2 class="h2">Faça o seu cadastro em nosso sistema</h2>
        <form id="booking-form" method="post" action="/registrar">
          <div class="row">
            <div class="col-lg-10 mx-auto">
              <div class="row">
                <input type="hidden" name="item" value="<?=$item?>">
                <label for="nome" class="col-md-12 unique">Nome
                    <input type="text" id="name" name="nome">
                </label>
                <label for="usuario" class="col-md-6 unique">Usuário
                  <input id="usuario" name="usuario" type="text" required="">
                </label>
                <label for="senha" class="col-md-6 unique">Senha
                  <input id="senha" name="senha" type="password" required="">
                </label>
                <div class="col-md-12">
                  <button type="submit" class="btn-unique">Cadastrar</button>
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
<!-- End Booking Section-->