<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Teste Devio - Full stack</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="/assets/vendor/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="/assets/vendor/font-awesome/css/font-awesome.min.css">
    <!-- Custom Font Icons-->
    <link rel="stylesheet" href="/assets/css/fontastic.css">
    <!-- owl carousel-->
    <link rel="stylesheet" href="/assets/vendor/owl.carousel/assets/owl.carousel.css">
    <link rel="stylesheet" href="/assets/vendor/owl.carousel/assets/owl.theme.default.css">
    <!-- air datepicker-->
    <link rel="stylesheet" href="/assets/vendor/air-datepicker/css/datepicker.min.css">
    <!-- lightbox-->
    <link rel="stylesheet" href="/assets/vendor/lightbox2/css/lightbox.min.css">
    <!-- timepicki-->
    <link rel="stylesheet" href="/assets/vendor/timepicki/css/timepicki.css">
    <!-- Slider-->
    <link rel="stylesheet" href="/assets/css/slider.min.css">
    <!-- google font - dancing script for headings | pt sans for copy-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Dancing+Script:400,700|PT+Serif:400,400i,700">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="/assets/css/style.violet.css" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="/assets/css/custom.css">
    <!-- Favicon-->
    <link rel="shortcut icon" href="/assets/img/devio_logo.jpg">
    <!-- Favicon-->
    <script src="/assets/js/modernizr.custom.79639.min.js"></script>
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
  <body>
    <?=$this->content();?>
    <script src="/assets/vendor/jquery/jquery.min.js"></script>
    <script src="/assets/vendor/popper.js/umd/popper.min.js"> </script>
    <script src="/assets/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="/assets/vendor/jquery.cookie/jquery.cookie.js"> </script>
    <script src="/assets/vendor/owl.carousel/owl.carousel.min.js"></script>
    <script src="/assets/js/jquery.ba-cond.min.js"></script>
    <script src="/assets/js/jquery.slitslider.min.js"></script>
    <script src="/assets/vendor/jquery-validation/jquery.validate.min.js"></script>
    <script src="/assets/vendor/lightbox2/js/lightbox.min.js"></script>
    <script src="/assets/vendor/timepicki/js/timepicki.js"></script>
    <script src="/assets/vendor/air-datepicker/js/datepicker.min.js"></script>
    <script src="/assets/vendor/air-datepicker/js/i18n/datepicker.en.js"></script>
    <script src="/assets/js/front.js"></script>
  
  </body>
</html>