<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Teste Devio - Full stack</title>
    <link rel="stylesheet" href="assets/css/custom.css">
    <link rel="shortcut icon" href="/assets/img/devio_logo.jpg">
</head>
<body>
    <div class="container-dev">
        <div class="row-dev">
            <a href="/admin_login" class="button-dev space">Cozinha</a>
        </div>
        <div class="row-dev">
            <a href="/cliente_acesso" class="button-dev space">Cliente</a>
        </div>
    </div>
</body>
</html>